// Generated by CoffeeScript 1.10.0
(function() {
  var CloudDrive, EventEmitter, app, express, opener, request, url,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  express = require('express');

  app = express();

  url = require('url');

  opener = require('opener');

  EventEmitter = require('events').EventEmitter;

  request = require('request');

  CloudDrive = (function(superClass) {
    extend(CloudDrive, superClass);

    function CloudDrive(options) {
      var callbackUrl, clientID, clientSecret, scopes, username;
      if (!(this instanceof CloudDrive)) {
        return new CloudDrive(options);
      }
      username = options.username, clientID = options.clientID, clientSecret = options.clientSecret, scopes = options.scopes, callbackUrl = options.callbackUrl;
      Object.defineProperties(this, {
        username: {
          value: username,
          writable: false,
          enumerable: false
        },
        clientID: {
          value: clientID,
          writable: false,
          enumerable: false
        },
        clientSecret: {
          value: clientSecret,
          writable: false,
          enumerable: false
        },
        scopes: {
          value: scopes || ['clouddrive:read_all', 'clouddrive:write'],
          writable: false,
          enumerable: false
        },
        callbackUrl: {
          value: callbackUrl || 'http://localhost:45002/cloud-drive-callback',
          writable: false,
          enumerable: false
        }
      });
    }

    CloudDrive.prototype.authenticate = function(cb) {
      var amazonOAUri, callbackUri, self;
      self = this;
      callbackUri = url.parse(this.callbackUrl);
      app.get(callbackUri.pathname, function(req, res, next) {
        if (req.query.error) {
          console.error('aws.cloud-drive-callback:error', req.query);
          res.status(400).json(req.query);
          return cb(req.query);
        } else {
          console.log('aws.cloud-drive-callback', req.query);
          res.json(req.query);
          return self.getOAuthToken(req.query, function(err, result) {
            if (err) {
              return cb(err);
            } else {
              return cb(null, result);
            }
          });
        }
      });
      app.listen(callbackUri.port);
      amazonOAUri = url.parse("https://www.amazon.com/ap/oa");
      amazonOAUri.query = {
        client_id: this.clientID,
        scope: this.scopes.join(' '),
        response_type: 'code',
        redirect_uri: this.callbackUrl
      };
      console.log('amazon-oa.uri', amazonOAUri);
      return opener(url.format(amazonOAUri));
    };

    CloudDrive.prototype.authRefresh = function(expiresSeconds) {
      var self, timeoutCallback;
      self = this;
      if (self.refreshID) {
        clearTimeout(self.refreshID);
      }
      timeoutCallback = function() {
        return self.refreshOAuthToken(function(err, res) {
          if (err) {
            return self.emit('error', err);
          } else {
            return self.emit('authenticated', res);
          }
        });
      };
      return self.refreshID = setTimeout(timeoutCallback, (expiresSeconds - 1) * 1000);
    };

    CloudDrive.prototype.refreshOAuthToken = function(cb) {
      var oAuthUrl, options, self;
      self = this;
      oAuthUrl = 'https://api.amazon.com/auth/o2/token';
      options = {
        method: 'POST',
        url: oAuthUrl,
        form: {
          grant_type: 'refresh_token',
          refresh_token: self.refreshToken,
          client_id: self.clientID,
          client_secret: self.clientSecret
        },
        json: true
      };
      console.log('AuthClient.refreshToken', options);
      return request(options, function(err, res, body) {
        if (err) {
          console.log('AuthClient.refreshToken:ERROR', err);
          return cb(err);
        } else if (res.statusCode >= 400) {
          console.log('AuthClient.refreshToken:HTTP_ERROR', res.statusCode, res.body);
          return cb(res.body);
        } else {
          self.accessToken = body.access_token;
          self.refreshToken = body.refresh_token;
          self.authRefresh(body.expires_in);
          return cb(null, body);
        }
      });
    };

    CloudDrive.prototype.getOAuthToken = function(arg, cb) {
      var code, oAuthUrl, options, self;
      code = arg.code;
      self = this;
      oAuthUrl = 'https://api.amazon.com/auth/o2/token';
      options = {
        method: 'POST',
        url: oAuthUrl,
        form: {
          grant_type: 'authorization_code',
          code: code,
          client_id: self.clientID,
          client_secret: self.clientSecret,
          redirect_uri: self.callbackUrl
        },
        json: true
      };
      console.log('AuthClient.getOAuthToken', options);
      return request(options, function(err, res, body) {
        if (err) {
          console.log('AuthClient.getOAuthToken:ERROR', err);
          return cb(err);
        } else if (res.statusCode >= 400) {
          console.log('AuthClient.getOAuthToken:HTTP_ERROR', res.statusCode, res.body);
          return cb(res.body);
        } else {
          body.code = code;
          self.code = code;
          self.accessToken = body.access_token;
          self.refreshToken = body.refresh_token;
          self.authRefresh(body.expires_in);
          return cb(null, body);
        }
      });
    };

    return CloudDrive;

  })(EventEmitter);

  module.exports = CloudDrive;

}).call(this);
